#!/usr/bin/with-contenv bash

UMASK_SET=${UMASK_SET:-022}
umask "$UMASK_SET"

cd /

if [ ! -z ${INTPORT} ]; then
	port=$INTPORT
else
	port=6595
fi

export DEEMIX_DATA_DIR=/config/
export DEEMIX_MUSIC_DIR=/downloads/
export DEEMIX_SERVER_PORT=$port
export DEEMIX_HOST=0.0.0.0

echo "[services.d] Starting Deemix"
s6-setuidgid abc node /deemix-gui/server/dist/app.js