#!/usr/bin/with-contenv bash

# download and unpack
echo "[cont-init.d] Downloading and unpacking"

if [ ! -f "/deemix/server.py" ]; then
    echo "[cont-init.d] First start, downloading repo"
    if [[ "${DEEZUI}" == "true" ]]; then
        echo "[cont-init.d] Using Deezloader UI"
        curl -L -o deemix_pyweb.zip http://gitlab.com/Bockiii/deemix-src/-/jobs/artifacts/master/download?job=dl_src
        unzip -qq deemix_pyweb.zip -d /
        rm -R /deemix/webui
        mv /deezui /deemix/webui
        touch /deemix/updated
    else
        echo "[cont-init.d] Using Deemix UI"
        curl -L -o deemix_pyweb.zip http://gitlab.com/Bockiii/deemix-src/-/jobs/artifacts/master/download?job=dl_src
        unzip -qq deemix_pyweb.zip -d /
        rm -R /deezui
        touch /deemix/updated
    fi
fi
