#!/usr/bin/with-contenv bash

# set home of the abc user
usermod -d /deem abc

# permissions
echo "[cont-init.d] Setting permissions this may take some time"

chown -R abc:abc \
 /deem/.config/

chown abc:abc \
 /downloads/