#!/usr/bin/with-contenv bash

# install deemix

if [ -f "/deemix/updated" ]; then
    echo "[cont-init.d] Installing"
    cd /deemix
    pip3 install -U -r requirements.txt --quiet --disable-pip-version-check
    rm /deemix/updated
    echo "[cont-init.d] Installation done"
fi

# check for arl environment variable. if it is set, create the arl file

if [ ${#ARL} -gt 10 ]; then
    echo "[cont-init.d] Using ARL token from environment variable"
    printf $ARL > /config/.arl
fi