#!/usr/bin/with-contenv bash

# install deemix

if [ -f "/deemix/updated" ]; then
    echo "[cont-init.d] Installing"
    cd /deemix
    sed -i '/^pyqt/d' requirements.txt
    pip3 install -U -r requirements.txt --quiet --disable-pip-version-check
    rm /deemix/updated
    echo "[cont-init.d] Installation done"
fi

# check for arl environment variable. if it is set, create the arl file.
# if the arl was previously set but is out of date, update the file with the arl from the env variable

if [ ${#ARL} -gt 10 ]; then
    OLDARL=$(cat /config/.arl)
    if $ARL -ne $OLDARL; then
        echo "[cont-init.d] !!! ARL from environment variable does not match current ARL. Using environment variable. !!!"
        echo "[cont-init.d] !!! Please update your ARL in the variable instead of the webinterface or remove the ARL from the container call. !!!"
        printf $ARL > /config/.arl
    fi
fi